@extends('layouts.guest')
@php($title = 'Kebijakan Privasi')
@section('content')
<article class="mx-auto max-w-4xl px-4 py-14 sm:px-6 sm:py-20">
    <div class="card overflow-hidden">
        <header class="border-b border-slate-200 bg-gradient-to-br from-violet-50 to-cyan-50 p-6 dark:border-white/10 dark:from-violet-500/10 dark:to-cyan-400/5 sm:p-10">
            <span class="badge bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300">Hukum</span>
            <h1 class="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Kebijakan Privasi</h1>
            <p class="mt-3 text-sm leading-7 text-slate-500 dark:text-slate-400">Terakhir diperbarui: 5 Agustus 2026</p>
        </header>
        <div class="space-y-9 p-6 text-sm leading-7 text-slate-600 dark:text-slate-400 sm:p-10">
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">1. Ruang Lingkup</h2><p class="mt-3">Kebijakan ini menjelaskan bagaimana {{ $siteName }} mengumpulkan, menggunakan, menyimpan, melindungi, dan membagikan informasi ketika Anda mengakses situs, membuat akun, membeli layanan nomor virtual, menerima SMS/OTP, melakukan pembayaran, menggunakan API pelanggan, atau menghubungi dukungan. Kebijakan ini berlaku untuk aktivitas daring pada platform kami.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">2. Persetujuan</h2><p class="mt-3">Dengan menggunakan layanan, Anda menyatakan telah membaca dan menyetujui Kebijakan Privasi ini. Apabila Anda tidak menyetujuinya, hentikan penggunaan layanan dan hubungi dukungan untuk pilihan yang tersedia terkait akun Anda.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">3. Informasi yang Kami Kumpulkan</h2><div class="mt-3 space-y-3"><p>Kami dapat mengumpulkan nama, nama pengguna, alamat email, nomor WhatsApp, ID Telegram, negara bawaan, kata sandi dalam bentuk hash, preferensi tema, status verifikasi, dan informasi akun lain yang Anda berikan.</p><p>Untuk menjalankan transaksi, kami memproses saldo, isi saldo, pesanan, layanan atau negara yang dipilih, nomor virtual, status aktivasi, kode OTP, waktu transaksi, pengembalian dana, dan catatan dukungan. Isi OTP disimpan secara terenkripsi dan hanya selama diperlukan untuk pemrosesan, keamanan, sengketa, atau kewajiban hukum.</p><p>Kami juga mencatat data teknis seperti alamat IP, jenis peramban, perangkat, waktu akses, halaman rujukan, agen pengguna, aktivitas sesi, permintaan API, status respons, dan log keamanan. Data tersebut digunakan untuk menjaga layanan, mencegah penyalahgunaan, dan menganalisis kinerja.</p></div></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">4. Cara Kami Menggunakan Informasi</h2><ul class="mt-3 list-disc space-y-2 pl-5"><li>menyediakan, mengoperasikan, dan memelihara platform;</li><li>memproses registrasi, verifikasi email, isi saldo, pesanan OTP, pengembalian dana, dan dukungan;</li><li>menampilkan status pesanan dan mengirimkan pembaruan yang relevan;</li><li>mengelola API key pelanggan dan mengautentikasi integrasi seperti bot Telegram;</li><li>meningkatkan pengalaman, keandalan, fitur, dan keamanan;</li><li>mendeteksi penipuan, spam, akses tidak sah, eksploitasi, atau pelanggaran ketentuan;</li><li>memenuhi kewajiban akuntansi, penyelesaian sengketa, audit, dan hukum.</li></ul></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">5. Penyedia Layanan dan Transfer Data</h2><p class="mt-3">Kami dapat meneruskan data terbatas kepada penyedia nomor virtual/SMS, penyedia pembayaran, email, hosting, basis data, pencadangan, pemantauan, dan keamanan hanya sejauh diperlukan untuk menjalankan layanan. API key penyedia tidak dikirim ke peramban atau pengguna. Masing-masing pihak dapat memiliki kebijakan privasi sendiri dan memproses data di negara lain sesuai infrastrukturnya.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">6. Kuki dan Penyimpanan Lokal</h2><p class="mt-3">Kami menggunakan kuki sesi dan penyimpanan lokal untuk proses masuk, keamanan, preferensi tema, status bilah sisi, dan fungsi penting lain. Anda dapat mengatur kuki melalui peramban, tetapi menonaktifkan kuki penting dapat membuat proses masuk atau fitur tertentu tidak berfungsi.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">7. Keamanan Data</h2><p class="mt-3">Kami menerapkan langkah yang wajar, termasuk hash kata sandi, enkripsi data sensitif, pembatasan akses, pembatasan laju, pencatatan audit, pemisahan API key pelanggan dari rahasia penyedia, dan pencabutan API key saat rotasi. Namun, tidak ada sistem internet yang dapat menjamin keamanan mutlak. Anda wajib menjaga kata sandi, API key, perangkat, dan sesi akun.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">8. Retensi dan Penghapusan</h2><p class="mt-3">Data disimpan selama akun aktif dan selama diperlukan untuk menyediakan layanan. Setelah permintaan penghapusan disetujui, akun dapat dinonaktifkan, sesi masuk dihapus, dan API key dicabut. Catatan transaksi, keamanan, penipuan, akuntansi, pengembalian dana, sengketa, dan audit dapat tetap disimpan sepanjang diperlukan atau diwajibkan hukum.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">9. Hak Pengguna</h2><p class="mt-3">Tergantung hukum yang berlaku, Anda dapat meminta akses, koreksi, pembatasan, keberatan, portabilitas, atau penghapusan data tertentu. Permintaan dapat diajukan melalui Pengaturan Akun atau dukungan. Kami dapat meminta verifikasi identitas dan menolak atau membatasi permintaan apabila penyimpanan data diperlukan untuk keamanan, transaksi, sengketa, atau hukum.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">10. Privasi Anak</h2><p class="mt-3">Layanan tidak ditujukan untuk anak di bawah usia yang diizinkan menurut hukum setempat dan kami tidak dengan sengaja mengumpulkan data anak. Orang tua atau wali yang meyakini seorang anak memberikan data kepada kami dapat menghubungi dukungan untuk peninjauan dan penghapusan yang sesuai.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">11. Perubahan Kebijakan</h2><p class="mt-3">Kami dapat memperbarui kebijakan ini dari waktu ke waktu. Versi terbaru akan dipublikasikan pada halaman ini bersama tanggal pembaruan. Perubahan material dapat disampaikan melalui situs, dasbor, atau email.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">12. Hubungi Kami</h2><p class="mt-3">Pertanyaan atau permintaan terkait privasi dapat disampaikan melalui menu Bantuan pada dasbor{{ filled($siteSupportWhatsapp) ? ' atau WhatsApp dukungan '.$siteSupportWhatsapp : '' }}.</p></section>
        </div>
    </div>
</article>
@endsection
