@extends('layouts.guest')
@php($title = 'Syarat dan Ketentuan')
@section('content')
<article class="mx-auto max-w-4xl px-4 py-14 sm:px-6 sm:py-20">
    <div class="card overflow-hidden">
        <header class="border-b border-slate-200 bg-gradient-to-br from-violet-50 to-cyan-50 p-6 dark:border-white/10 dark:from-violet-500/10 dark:to-cyan-400/5 sm:p-10">
            <span class="badge bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300">Hukum</span>
            <h1 class="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Syarat dan Ketentuan</h1>
            <p class="mt-3 text-sm leading-7 text-slate-500 dark:text-slate-400">Terakhir diperbarui: 5 Agustus 2026</p>
        </header>
        <div class="space-y-9 p-6 text-sm leading-7 text-slate-600 dark:text-slate-400 sm:p-10">
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">1. Ketentuan Umum</h2><p class="mt-3">Dengan mendaftar atau menggunakan {{ $siteName }}, Anda menyetujui seluruh syarat ini dan Kebijakan Privasi. Kami dapat memperbarui ketentuan untuk menyesuaikan layanan, penyedia, keamanan, atau hukum. Versi terbaru berlaku sejak dipublikasikan, kecuali dinyatakan lain.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">2. Fungsi Layanan</h2><p class="mt-3">Platform menyediakan akses sementara untuk menerima SMS/OTP dari aplikasi yang Anda pilih. Layanan bukan nomor telepon permanen, tidak menjamin pembuatan atau keamanan akun pihak ketiga, dan tidak menjamin bahwa setiap platform akan menerima nomor virtual. Ketersediaan, operator, harga, stok, dan waktu pengiriman bergantung pada penyedia serta aplikasi tujuan.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">3. Penggunaan yang Diizinkan</h2><p class="mt-3">Anda hanya boleh memakai layanan untuk tujuan yang sah dan sesuai ketentuan aplikasi tujuan. Dilarang menggunakan layanan untuk penipuan, pengelabuan, spam, pelecehan, penyamaran, pengambilalihan akun, menghindari sanksi atau pembatasan platform, manipulasi promosi, aktivitas otomatis yang merugikan, atau tindakan yang melanggar hukum dan hak pihak lain.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">4. Akun dan Keamanan</h2><p class="mt-3">Anda bertanggung jawab atas kebenaran data akun, kerahasiaan kata sandi, API key, perangkat, dan seluruh aktivitas yang terjadi melalui akun Anda. Jangan membagikan OTP atau API key. Segera rotasi API key, ubah kata sandi, dan hubungi dukungan bila menduga terjadi kebocoran. Kami dapat membatasi atau menangguhkan akun untuk investigasi keamanan.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">5. Pemesanan, Harga, dan Saldo</h2><p class="mt-3">Harga ditampilkan dalam Rupiah dan dapat berubah sewaktu-waktu berdasarkan harga penyedia, kurs atau konversi, markup, stok, dan pembulatan. Harga yang berlaku adalah harga saat pesanan dibuat. Saldo akan didebit ketika pesanan diterima. Setiap pesanan API wajib memakai kunci idempotensi unik agar pengulangan permintaan tidak membuat pesanan ganda.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">6. Pembatalan dan Pengembalian Dana</h2><p class="mt-3">Pesanan yang telah menerima OTP, selesai, atau telah digunakan tidak dapat dikembalikan dananya, kecuali diwajibkan hukum. Pengembalian dana dapat diberikan untuk pesanan gagal, dibatalkan, atau status lain yang disetujui penyedia dan sistem. Pengguna harus membatalkan sebelum waktu habis apabila opsi tersebut tersedia. Keterlambatan penyedia, kelebihan beban, atau blokir dari aplikasi tujuan tidak otomatis menjamin pengembalian dana.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">7. Penggunaan Wajar dan API</h2><p class="mt-3">Untuk menjaga ketersediaan, kami dapat menerapkan batas permintaan, jumlah pesanan, pemeriksaan status berkala, penggunaan ulang, atau pola transaksi. Penggunaan API yang membebani sistem, melakukan pengambilan data otomatis secara berlebihan, mencoba menebak API key, mengeksploitasi idempotensi, atau mengganggu pengguna lain dapat menyebabkan pembatasan, pencabutan API key, biaya tambahan yang sah, atau penangguhan akun.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">8. Layanan Pihak Ketiga</h2><p class="mt-3">Platform bergantung pada penyedia nomor virtual, aplikasi tujuan, jaringan telekomunikasi, pembayaran, email, hosting, dan layanan pihak ketiga. Kami tidak mengendalikan kebijakan blokir, penghapusan akun, penangguhan, keterlambatan, atau kegagalan pihak tersebut. Penggunaan layanan kami tidak menjamin akun Anda pada platform lain tetap aktif.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">9. Penangguhan dan Penghapusan Akun</h2><p class="mt-3">Kami dapat menangguhkan atau menutup akses apabila terdapat dugaan penyalahgunaan, penipuan, pembalikan pembayaran, pelanggaran ketentuan, risiko keamanan, permintaan hukum, atau akun tidak aktif sesuai kebijakan operasional yang dipublikasikan. Permintaan penghapusan pengguna ditinjau admin sebelum akun dinonaktifkan, sesi dihapus, dan API key dicabut.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">10. Batasan Tanggung Jawab</h2><p class="mt-3">Sejauh diizinkan hukum, layanan diberikan “sebagaimana adanya” dan “sebagaimana tersedia”. Kami tidak bertanggung jawab atas kehilangan akun pihak ketiga, keuntungan, data, peluang bisnis, reputasi, atau kerugian tidak langsung yang timbul dari penggunaan nomor virtual, keterlambatan OTP, kegagalan penyedia, atau pelanggaran pengguna. Tanggung jawab langsung kami, bila ada, dibatasi pada nilai transaksi terkait.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">11. Ganti Rugi</h2><p class="mt-3">Anda setuju bertanggung jawab atas klaim, kerugian, biaya, atau tuntutan yang muncul dari penggunaan layanan secara melanggar hukum, pelanggaran syarat ini, atau pelanggaran hak pihak lain.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">12. Hukum dan Penyelesaian Sengketa</h2><p class="mt-3">Sengketa sebaiknya terlebih dahulu diselesaikan melalui dukungan dengan menyertakan bukti transaksi. Ketentuan ini tunduk pada hukum yang berlaku bagi operator platform, tanpa mengurangi hak konsumen yang tidak dapat dikesampingkan.</p></section>
            <section><h2 class="text-xl font-black text-slate-900 dark:text-white">13. Kontak</h2><p class="mt-3">Pertanyaan mengenai ketentuan dapat disampaikan melalui menu Bantuan pada dasbor{{ filled($siteSupportWhatsapp) ? ' atau WhatsApp dukungan '.$siteSupportWhatsapp : '' }}.</p></section>
        </div>
    </div>
</article>
@endsection
