@extends('layouts.app')
@php($title = 'Pengaturan')
@php($tabs = ['site'=>'Situs','auth'=>'Verifikasi','orders'=>'Pesanan','pricing'=>'Harga','topup'=>'Top Up','sms_virtual'=>'SMS Virtual','pakasir'=>'Pakasir','mail'=>'SMTP','security'=>'Keamanan'])
@php($v = fn($key,$default='') => old($key, $values[$tab.'.'.$key] ?? $default))
@section('content')
<div><h1 class="text-3xl font-black">Pengaturan sistem</h1><p class="mt-2 text-sm text-slate-500">Konfigurasi disimpan di database; nilai rahasia dienkripsi menggunakan APP_KEY.</p></div>
<div class="mt-6 flex gap-2 overflow-x-auto pb-2">@foreach($tabs as $key=>$label)<a class="{{ $tab===$key?'btn-primary':'btn-secondary' }} whitespace-nowrap" href="{{ route('admin.settings.index',['tab'=>$key]) }}">{{ $label }}</a>@endforeach</div>
<div class="mt-4 grid gap-6 xl:grid-cols-3"><form class="card space-y-5 p-6 xl:col-span-2" method="post" action="{{ route('admin.settings.update') }}">@csrf @method('put')<input type="hidden" name="group" value="{{ $tab }}">
@if($tab==='site')
<div><label class="label">Nama situs</label><input class="input" name="name" value="{{ $v('name') }}" required></div><div><label class="label">Deskripsi SEO</label><textarea class="input min-h-28" name="description" required>{{ $v('description') }}</textarea></div><div><label class="label">WhatsApp dukungan</label><input class="input" name="support_whatsapp" value="{{ $v('support_whatsapp') }}" placeholder="62812..."></div>
@elseif($tab==='auth')
<div><label class="label">Masa berlaku OTP email (menit)</label><input class="input" type="number" name="email_otp_expiry_minutes" min="3" max="60" value="{{ $v('email_otp_expiry_minutes',10) }}" required></div><div><label class="label">Jeda kirim ulang (detik)</label><input class="input" type="number" name="email_otp_resend_seconds" min="30" max="600" value="{{ $v('email_otp_resend_seconds',60) }}" required></div>
@elseif($tab==='orders')
<div><label class="label">Fallback kedaluwarsa pesanan (menit)</label><input class="input" type="number" name="default_expiry_minutes" min="5" max="180" value="{{ $v('default_expiry_minutes',20) }}" required><p class="mt-1 text-xs text-slate-500">Hanya dipakai jika provider tidak mengirim timestamp kedaluwarsa.</p></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="refund_on_expired" value="1" @checked((bool)$v('refund_on_expired',false))> Refund otomatis ketika status provider kedaluwarsa</label>
@elseif($tab==='pricing')
<div><label class="label">Markup persentase</label><input class="input" type="number" step="0.01" name="markup_percent" min="0" max="500" value="{{ $v('markup_percent',10) }}" required><p class="mt-1 text-xs text-slate-500">Contoh modal Rp5.000 + 10% = Rp5.500 sebelum pembulatan.</p></div><div><label class="label">Biaya tetap</label><input class="input" type="number" name="fixed_fee" min="0" value="{{ $v('fixed_fee',0) }}" required></div><div><label class="label">Pembulatan harga</label><select class="input" name="round_to">@foreach([1,10,100,500,1000] as $round)<option value="{{ $round }}" @selected((int)$v('round_to',100)===$round)>Rp {{ number_format($round,0,',','.') }}</option>@endforeach</select></div>
@elseif($tab==='topup')
<div><label class="label">Minimum top up</label><input class="input" type="number" name="minimum" value="{{ $v('minimum',10000) }}" required></div><div><label class="label">Maksimum top up</label><input class="input" type="number" name="maximum" value="{{ $v('maximum',5000000) }}" required></div><div><label class="label">Metode default</label><input class="input" name="payment_method" value="{{ $v('payment_method','qris') }}" required></div>
@elseif($tab==='sms_virtual')
<div><label class="label">Base URL</label><input class="input" type="url" name="base_url" value="{{ $v('base_url','https://api.sms-virtual.net') }}" required></div><div><label class="label">API key</label><input class="input" type="password" name="api_key" value="" placeholder="Kosongkan untuk mempertahankan API key saat ini"><p class="mt-1 text-xs text-slate-500">Disimpan terenkripsi dan hanya dipakai pada request backend.</p></div><div><label class="label">Timeout (detik)</label><input class="input" type="number" name="timeout" min="5" max="120" value="{{ $v('timeout',30) }}" required></div>
@elseif($tab==='pakasir')
<div><label class="label">Base URL</label><input class="input" type="url" name="base_url" value="{{ $v('base_url','https://app.pakasir.com') }}" required></div><div><label class="label">Project slug</label><input class="input" name="project" value="{{ $v('project') }}" required></div><div><label class="label">API key</label><input class="input" type="password" name="api_key" value="" placeholder="Kosongkan untuk mempertahankan API key saat ini"></div><div><label class="label">Metode default</label><input class="input" name="payment_method" value="{{ $v('payment_method','qris') }}" required></div>
@elseif($tab==='mail')
<div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Mailer</label><input class="input" name="mailer" value="{{ $v('mailer','smtp') }}" required></div><div><label class="label">Host SMTP</label><input class="input" name="host" value="{{ $v('host') }}" required></div><div><label class="label">Port</label><input class="input" type="number" name="port" value="{{ $v('port',587) }}" required></div><div><label class="label">Enkripsi</label><select class="input" name="encryption"><option value="" @selected($v('encryption')==='')>Tanpa enkripsi</option><option value="tls" @selected($v('encryption','tls')==='tls')>TLS / STARTTLS</option><option value="ssl" @selected($v('encryption')==='ssl')>SSL</option></select></div><div><label class="label">Username</label><input class="input" name="username" value="{{ $v('username') }}"></div><div><label class="label">Password</label><input class="input" type="password" name="password" value="" placeholder="Kosongkan untuk mempertahankan password"></div><div><label class="label">Alamat pengirim</label><input class="input" type="email" name="from_address" value="{{ $v('from_address') }}" required></div><div><label class="label">Nama pengirim</label><input class="input" name="from_name" value="{{ $v('from_name') }}" required></div></div>
@elseif($tab==='security')
<div><label class="label">Secret webhook SMS Virtual</label><input class="input" type="password" name="provider_webhook_secret" value="" placeholder="Minimal 24 karakter; kosongkan untuk mempertahankan"><p class="mt-1 text-xs text-slate-500">Digunakan pada URL webhook internal aplikasi. Pakai secret acak panjang dan jangan bagikan.</p></div>
@endif
<button class="btn-primary">Simpan {{ $tabs[$tab] }}</button></form>
<aside class="space-y-4"><section class="card p-5"><h2 class="font-bold">Tes & sinkronisasi</h2><div class="mt-4 grid gap-2"><form method="post" action="{{ route('admin.settings.test-sms') }}">@csrf<button class="btn-secondary w-full">Tes saldo SMS Virtual</button></form><form method="post" action="{{ route('admin.settings.sync-catalog') }}">@csrf<button class="btn-secondary w-full">Sinkronkan katalog langsung</button></form><form method="post" action="{{ route('admin.settings.test-pakasir') }}">@csrf<button class="btn-secondary w-full">Tes konfigurasi Pakasir</button></form><form method="post" action="{{ route('admin.settings.test-mail') }}">@csrf<button class="btn-secondary w-full">Kirim email uji langsung</button></form></div></section><section class="card p-5 text-sm leading-6 text-slate-500"><h2 class="font-bold text-slate-800 dark:text-slate-100">Catatan keamanan</h2><p class="mt-2">DevTools tetap dapat melihat URL endpoint aplikasi Anda, tetapi tidak melihat API key atau request langsung ke provider. Jangan menaruh secret di JavaScript, Blade, repository, atau konfigurasi Caddy publik.</p></section></aside></div>
@endsection
