<?php

return [
    'defaults' => [
        'site.name' => env('APP_NAME', 'KodeOTP'),
        'site.description' => 'Layanan penerimaan kode OTP virtual yang cepat, transparan, dan mudah digunakan.',
        'site.support_whatsapp' => '',
        'site.logo_url' => '',
        'site.seo_title' => '',
        'site.seo_description' => '',
        'site.seo_keywords' => '',
        'site.seo_hashtags' => '',
        'site.seo_image_url' => '',
        'auth.email_otp_expiry_minutes' => 10,
        'auth.email_otp_resend_seconds' => 60,
        'orders.default_expiry_minutes' => 20,
        'orders.refund_on_expired' => false,
        'pricing.markup_percent' => 10,
        'pricing.fixed_fee' => 0,
        'pricing.round_to' => 100,
        'topup.minimum' => 10000,
        'topup.maximum' => 5000000,
        'topup.payment_method' => env('PAKASIR_PAYMENT_METHOD', 'qris'),
        'payments.active_gateway' => env('PAYMENT_GATEWAY', 'pakasir'),
        'payments.pending_gateway' => null,
        'payments.pending_requested_at' => null,
        'payments.pending_requested_by' => null,
        'sms_virtual.base_url' => env('SMS_VIRTUAL_BASE_URL', 'https://api.sms-virtuals.net'),
        'sms_virtual.api_key' => env('SMS_VIRTUAL_API_KEY', ''),
        'sms_virtual.timeout' => (int) env('SMS_VIRTUAL_TIMEOUT', 30),
        'sms_virtual.low_balance_threshold' => (float) env('SMS_VIRTUAL_LOW_BALANCE_THRESHOLD', 5000),
        'sms_virtual.reserve_buffer_percent' => (float) env('SMS_VIRTUAL_RESERVE_BUFFER_PERCENT', 20),
        'pakasir.base_url' => env('PAKASIR_BASE_URL', 'https://app.pakasir.com'),
        'pakasir.project' => env('PAKASIR_PROJECT', ''),
        'pakasir.api_key' => env('PAKASIR_API_KEY', ''),
        'pakasir.payment_method' => env('PAKASIR_PAYMENT_METHOD', 'qris'),
        'duitku.environment' => env('DUITKU_ENVIRONMENT', 'production'),
        'duitku.merchant_code' => env('DUITKU_MERCHANT_CODE', ''),
        'duitku.api_key' => env('DUITKU_API_KEY', ''),
        'duitku.payment_method' => env('DUITKU_PAYMENT_METHOD', 'NQ'),
        'duitku.expiry_minutes' => (int) env('DUITKU_EXPIRY_MINUTES', 10),
        'mail.mailer' => env('MAIL_MAILER', 'smtp'),
        'mail.host' => env('MAIL_HOST', ''),
        'mail.port' => env('MAIL_PORT', 587),
        'mail.username' => env('MAIL_USERNAME', ''),
        'mail.password' => env('MAIL_PASSWORD', ''),
        'mail.encryption' => env('MAIL_ENCRYPTION', 'tls'),
        'mail.from_address' => env('MAIL_FROM_ADDRESS', 'no-reply@example.com'),
        'mail.from_name' => env('MAIL_FROM_NAME', env('APP_NAME', 'KodeOTP')),
        'security.provider_webhook_secret' => env('OTP_GATEWAY_SECRET', ''),
    ],
    'secret_keys' => [
        'sms_virtual.api_key',
        'pakasir.api_key',
        'duitku.api_key',
        'mail.password',
        'security.provider_webhook_secret',
    ],
    'backup_max_mb' => (int) env('BACKUP_MAX_MB', 100),
];
