@extends('layouts.app')
@php($title = 'API Docs')
@section('content')
<div><span class="badge bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300">API</span><h1 class="section-title mt-4">API Integration</h1><p class="section-copy">Arsitektur KodeOTP menjaga API key SMS Virtual tetap berada di backend. Browser dan pengguna tidak pernah menerima secret provider.</p></div>
<div class="mt-7 grid gap-6 lg:grid-cols-3">
<section class="card p-6 lg:col-span-2"><div class="flex items-center gap-3"><span class="grid size-12 place-items-center rounded-2xl bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300"><x-icon name="api" size="size-6" /></span><div><h2 class="text-lg font-black">Status API pelanggan</h2><p class="text-xs text-slate-500">Endpoint publik untuk integrasi pelanggan belum diaktifkan.</p></div></div><div class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800 dark:border-amber-400/20 dark:bg-amber-400/10 dark:text-amber-200">Saat ini pembelian OTP dilakukan melalui dashboard agar saldo, idempotensi, dan kontrol risiko tetap konsisten. Menu ini disiapkan untuk dokumentasi API pelanggan pada versi berikutnya.</div><div class="mt-6 grid gap-4 sm:grid-cols-3">@foreach([['Authentication','Token pelanggan akan terpisah dari API key provider.'],['Idempotency','Setiap order API wajib menggunakan kunci unik.'],['Webhook','Status OTP dapat dikirim ke URL callback pelanggan.']] as $item)<article class="card-soft p-4"><h3 class="font-black">{{ $item[0] }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $item[1] }}</p></article>@endforeach</div></section>
<aside class="card p-6"><h2 class="font-black">Akses yang tersedia</h2><div class="mt-5 grid gap-3"><a href="{{ route('services.index') }}" class="btn-secondary justify-between">Katalog layanan <x-icon name="arrow-right" size="size-4" /></a><a href="{{ route('orders.index') }}" class="btn-secondary justify-between">Status pesanan <x-icon name="arrow-right" size="size-4" /></a><a href="{{ route('support.index') }}" class="btn-secondary justify-between">Ajukan integrasi <x-icon name="arrow-right" size="size-4" /></a></div></aside>
</div>
@endsection
