@extends('layouts.app')
@php($title = 'Dashboard')
@section('content')
<div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-500">Selamat datang kembali,</p><h1 class="text-3xl font-black tracking-tight">{{ $user->name }}</h1></div><a class="btn-primary" href="{{ route('services.index') }}">Beli layanan OTP</a></div>
<div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="stat"><div class="text-sm text-slate-500">Saldo</div><div class="mt-2 text-2xl font-black">Rp {{ number_format((float)$user->balance,0,',','.') }}</div></div><div class="stat"><div class="text-sm text-slate-500">Pesanan aktif</div><div class="mt-2 text-2xl font-black">{{ $activeOrders->count() }}</div></div><div class="stat"><div class="text-sm text-slate-500">Top up menunggu</div><div class="mt-2 text-2xl font-black">{{ $pendingTopups->count() }}</div></div><div class="stat"><div class="text-sm text-slate-500">Status akun</div><div class="mt-2"><x-status :value="$user->status" /></div></div></div>
<div class="mt-6 grid gap-6 xl:grid-cols-3">
    <section class="card p-5 xl:col-span-2"><div class="flex items-center justify-between"><h2 class="text-lg font-bold">Pesanan aktif</h2><a class="text-sm font-semibold text-brand-600 dark:text-brand-300" href="{{ route('orders.index') }}">Semua</a></div><div class="mt-4 space-y-3">@forelse($activeOrders as $order)<a href="{{ route('orders.show',$order) }}" class="flex flex-col justify-between gap-3 rounded-xl border border-slate-200 p-4 transition hover:border-brand-400 dark:border-white/10 sm:flex-row sm:items-center"><div><div class="font-semibold">{{ $order->service_name }} · {{ $order->country_name }}</div><div class="mt-1 text-xs text-slate-500">{{ $order->phone_number ?: 'Nomor sedang disiapkan' }}</div></div><x-status :value="$order->status" /></a>@empty<div class="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500 dark:border-white/10">Belum ada pesanan aktif.</div>@endforelse</div></section>
    <section class="card p-5"><div class="flex items-center justify-between"><h2 class="text-lg font-bold">Pengumuman</h2><a class="text-sm font-semibold text-brand-600 dark:text-brand-300" href="{{ route('announcements.index') }}">Semua</a></div><div class="mt-4 space-y-4">@forelse($announcements as $item)<div><div class="flex items-center gap-2"><h3 class="font-semibold">{{ $item->title }}</h3>@if($item->is_pinned)<span title="Disematkan">★</span>@endif</div><p class="mt-1 line-clamp-2 text-sm text-slate-500">{{ $item->body }}</p></div>@empty<p class="text-sm text-slate-500">Tidak ada pengumuman.</p>@endforelse</div></section>
</div>
<section class="card mt-6 p-5"><h2 class="text-lg font-bold">Mutasi terbaru</h2><div class="mt-4 table-wrap"><table class="table"><thead><tr><th>Waktu</th><th>Keterangan</th><th>Arah</th><th>Nominal</th><th>Saldo</th></tr></thead><tbody>@forelse($recentTransactions as $tx)<tr><td>{{ $tx->created_at->format('d M Y H:i') }}</td><td>{{ $tx->description }}</td><td><x-status :value="$tx->direction" /></td><td class="font-semibold {{ $tx->direction==='credit' ? 'text-emerald-500':'text-rose-500' }}">{{ $tx->direction==='credit'?'+':'-' }} Rp {{ number_format((float)$tx->amount,0,',','.') }}</td><td>Rp {{ number_format((float)$tx->balance_after,0,',','.') }}</td></tr>@empty<tr><td colspan="5" class="text-center text-slate-500">Belum ada mutasi.</td></tr>@endforelse</tbody></table></div></section>
@endsection
