@extends('layouts.app')
@php($title = 'Detail Pesanan')
@section('content')
<div x-data="orderStatus(@js(route('orders.status',$order)), @js(['status'=>$order->status,'phone_number'=>$order->phone_number,'otp_code'=>$order->otp_code,'message'=>$order->provider_message,'expires_at'=>$order->expires_at?->toIso8601String(),'terminal'=>$order->isTerminal()]))">
<div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a class="text-sm text-brand-600 dark:text-brand-300" href="{{ route('orders.index') }}">← Kembali</a><h1 class="mt-2 text-3xl font-black tracking-tight">{{ $order->service_name }}</h1><p class="mt-2 text-sm text-slate-500">{{ $order->country_name }} · {{ $order->operator_name ?: 'Semua operator' }}</p></div><x-status x-bind:data-status="data.status" :value="$order->status" /></div>
<div class="mt-6 grid gap-6 lg:grid-cols-3"><section class="card p-6 lg:col-span-2"><div class="grid gap-5 sm:grid-cols-2"><div><div class="text-xs uppercase tracking-wider text-slate-500">Nomor</div><div class="mt-2 flex items-center gap-2"><span class="break-all text-2xl font-black" x-text="data.phone_number || 'Sedang disiapkan...'">{{ $order->phone_number }}</span><button x-show="data.phone_number" @click="copy(data.phone_number)" class="btn-secondary !px-2 !py-1">Salin</button></div></div><div><div class="text-xs uppercase tracking-wider text-slate-500">Kode OTP</div><div class="mt-2 flex items-center gap-2"><span class="break-all text-3xl font-black tracking-widest text-brand-600 dark:text-brand-300" x-text="data.otp_code || '———'">{{ $order->otp_code }}</span><button x-show="data.otp_code" @click="copy(data.otp_code)" class="btn-secondary !px-2 !py-1">Salin</button></div></div></div><div class="mt-6 rounded-xl border border-slate-200 p-4 dark:border-white/10"><div class="text-xs uppercase tracking-wider text-slate-500">Pesan provider</div><p class="mt-2 whitespace-pre-line text-sm" x-text="data.message || 'Menunggu pembaruan status...'">{{ $order->provider_message }}</p></div><div class="mt-5 text-sm text-slate-500">Sisa waktu: <strong x-text="countdown">—</strong></div></section>
<section class="card p-6"><h2 class="font-bold">Ringkasan</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-3"><dt class="text-slate-500">Status</dt><dd class="font-semibold" x-text="data.status">{{ $order->status }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Harga</dt><dd class="font-semibold">Rp {{ number_format((float)$order->sell_price,0,',','.') }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Dibuat</dt><dd>{{ $order->created_at->format('d M Y H:i') }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Activation ID</dt><dd class="max-w-40 truncate">{{ $order->provider_activation_id ?: '—' }}</dd></div></dl><div class="mt-6 grid gap-2">@foreach(['ready'=>'SMS dikirim','resend'=>'Kirim ulang','complete'=>'Selesaikan','cancel'=>'Batalkan','reactivate'=>'Aktifkan ulang'] as $action=>$label)<form method="post" action="{{ route('orders.action',$order) }}">@csrf<input type="hidden" name="action" value="{{ $action }}"><button class="{{ $action==='cancel'?'btn-danger':'btn-secondary' }} w-full" @disabled(! $order->provider_activation_id || ($order->isTerminal() && $action!=='reactivate'))>{{ $label }}</button></form>@endforeach</div></section></div>
<p x-show="copied" x-transition class="fixed bottom-5 right-5 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-xl">Disalin ke clipboard</p></div>
@push('head')<script>document.addEventListener('alpine:init',()=>Alpine.data('orderStatus',(url,initial)=>({data:initial,countdown:'—',copied:false,timer:null,init(){this.tick();this.timer=setInterval(()=>{this.tick();if(!this.data.terminal)this.fetch()},5000)},async fetch(){try{this.data=(await axios.get(url)).data}catch(e){}},tick(){if(!this.data.expires_at){this.countdown='—';return}const s=Math.max(0,Math.floor((new Date(this.data.expires_at)-new Date())/1000));this.countdown=`${Math.floor(s/60)}m ${s%60}s`},async copy(v){await navigator.clipboard.writeText(v);this.copied=true;setTimeout(()=>this.copied=false,1400)}})))</script>@endpush
@endsection
