@extends('layouts.app')
@php($title = 'Profil')
@section('content')
<div><span class="badge bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300">Profile</span><h1 class="section-title mt-4">Account Settings</h1><p class="section-copy">Kelola identitas akun, email, tema tampilan, dan password.</p></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2">
<section class="card p-6"><div class="flex items-center gap-3"><span class="grid size-11 place-items-center rounded-2xl bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300"><x-icon name="user" /></span><div><h2 class="text-lg font-black">Informasi akun</h2><p class="text-xs text-slate-500">Data utama yang digunakan pada dashboard.</p></div></div><form class="mt-6 space-y-4" method="post" action="{{ route('profile.update') }}">@csrf @method('put')<div><label class="label">Nama</label><input class="input" name="name" value="{{ old('name',$user->name) }}" required></div><div><label class="label">Username</label><input class="input" name="username" value="{{ old('username',$user->username) }}" required></div><div><label class="label">WhatsApp</label><input class="input" name="whatsapp" value="{{ old('whatsapp',$user->whatsapp) }}" required></div><div><label class="label">Email</label><input class="input" type="email" name="email" value="{{ old('email',$user->email) }}" required><p class="mt-1 text-xs text-slate-500">Mengubah email mewajibkan verifikasi ulang.</p></div><div><label class="label">Tema default</label><select class="input" name="theme" @change="$store.theme.set($event.target.value)"><option value="light" @selected(old('theme',$user->theme)==='light')>Light</option><option value="dark" @selected(old('theme',$user->theme)==='dark')>Dark</option></select><p class="mt-1 text-xs text-slate-500">Tema langsung diterapkan dan disimpan pada browser.</p></div><button class="btn-primary">Simpan profil</button></form></section>
<section class="card p-6"><div class="flex items-center gap-3"><span class="grid size-11 place-items-center rounded-2xl bg-cyan-100 text-cyan-700 dark:bg-cyan-400/10 dark:text-cyan-300"><x-icon name="shield" /></span><div><h2 class="text-lg font-black">Ubah password</h2><p class="text-xs text-slate-500">Gunakan password unik dan kuat.</p></div></div><form class="mt-6 space-y-4" method="post" action="{{ route('profile.password') }}">@csrf @method('put')<div><label class="label">Password saat ini</label><input class="input" type="password" name="current_password" required></div><div><label class="label">Password baru</label><input class="input" type="password" name="password" required></div><div><label class="label">Ulangi password baru</label><input class="input" type="password" name="password_confirmation" required></div><button class="btn-primary">Perbarui password</button></form><div class="mt-8 rounded-2xl border border-slate-200 p-4 text-sm leading-6 text-slate-500 dark:border-white/10"><strong class="text-slate-700 dark:text-slate-200">Keamanan:</strong> jangan membagikan password, kode OTP, atau sesi akun kepada siapa pun.</div></section>
</div>
@endsection
