@extends('layouts.app')
@php($title = 'Layanan OTP')
@section('content')
<div><h1 class="text-3xl font-black tracking-tight">Layanan OTP</h1><p class="mt-2 text-sm text-slate-500">Pilih berdasarkan negara, stok, operator, dan harga saat ini.</p></div>
<form class="card mt-6 grid gap-3 p-4 md:grid-cols-5" method="get"><input class="input md:col-span-2" name="q" value="{{ request('q') }}" placeholder="Cari aplikasi..."><select class="input" name="country"><option value="">Semua negara</option>@foreach($countries as $country)<option value="{{ $country->id }}" @selected(request('country')==$country->id)>{{ $country->name }}</option>@endforeach</select><select class="input" name="sort"><option value="">Harga termurah</option><option value="price_desc" @selected(request('sort')==='price_desc')>Harga tertinggi</option><option value="stock" @selected(request('sort')==='stock')>Stok terbanyak</option><option value="success" @selected(request('sort')==='success')>Sukses tertinggi</option></select><button class="btn-primary">Terapkan</button><label class="flex items-center gap-2 text-sm text-slate-500 md:col-span-5"><input type="checkbox" name="stock" value="1" @checked(request('stock'))> Hanya yang tersedia</label></form>
<div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
@forelse($prices as $price)
<article class="card flex flex-col p-5"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><h2 class="truncate text-lg font-bold">{{ $price->service?->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $price->country?->name }} · {{ $price->operator_name ?: 'Semua operator' }}</p></div><span class="badge {{ $price->stock>0?'bg-emerald-500/10 text-emerald-600 dark:text-emerald-300':'bg-rose-500/10 text-rose-600 dark:text-rose-300' }}">{{ $price->stock }} stok</span></div><div class="mt-6 text-2xl font-black text-brand-600 dark:text-brand-300">Rp {{ number_format((float)$price->sell_price,0,',','.') }}</div><div class="mt-2 text-xs text-slate-500">Tingkat sukses {{ $price->success_rate !== null ? number_format((float)$price->success_rate,1).'%' : '—' }}</div><form class="mt-5" method="post" action="{{ route('orders.store') }}">@csrf<input type="hidden" name="price_id" value="{{ $price->id }}"><input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}"><button class="btn-primary w-full" @disabled($price->stock<1)>{{ $price->stock>0?'Pesan sekarang':'Stok habis' }}</button></form></article>
@empty<div class="card col-span-full p-10 text-center text-slate-500">Tidak ada layanan yang sesuai filter.</div>@endforelse
</div><div class="mt-8">{{ $prices->links() }}</div>
@endsection
