@extends('layouts.app')
@php($title = 'Tickets & Support')
@section('content')
<div><span class="badge bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300">Tickets</span><h1 class="section-title mt-4">Tickets & Support</h1><p class="section-copy">Butuh bantuan terkait order, saldo, pembayaran, atau integrasi? Hubungi administrator melalui kanal dukungan resmi.</p></div>
<div class="mt-7 grid gap-6 lg:grid-cols-[1fr_360px]">
<section class="card p-6"><h2 class="text-lg font-black">Pilih topik bantuan</h2><div class="mt-5 grid gap-4 sm:grid-cols-2">@foreach([['orders','Order & OTP','Nomor belum muncul, OTP terlambat, resend, atau pembatalan.'],['topup','Top Up & Deposit','Invoice, QRIS, virtual account, atau saldo belum masuk.'],['wallet','Saldo & Mutasi','Pengecekan saldo, refund, atau transaksi wallet.'],['api','API Integration','Permintaan akses API pelanggan atau webhook.']] as $item)<article class="card-soft p-5"><span class="grid size-11 place-items-center rounded-2xl bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300"><x-icon :name="$item[0]" /></span><h3 class="mt-4 font-black">{{ $item[1] }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $item[2] }}</p></article>@endforeach</div></section>
<aside class="card p-6"><span class="grid size-12 place-items-center rounded-2xl bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><x-icon name="ticket" size="size-6" /></span><h2 class="mt-5 text-xl font-black">Buat tiket dukungan</h2><p class="mt-3 text-sm leading-6 text-slate-500">Sertakan email akun, ID order/top up, waktu kejadian, dan tangkapan layar. Jangan pernah mengirim password atau kode OTP.</p>@if(filled($siteSupportWhatsapp))<a target="_blank" rel="noopener" href="https://wa.me/{{ preg_replace('/\D+/', '', $siteSupportWhatsapp) }}?text={{ urlencode('Halo '.$siteName.', saya membutuhkan bantuan terkait akun OTP.') }}" class="btn-primary mt-6 w-full">Hubungi via WhatsApp <x-icon name="arrow-right" size="size-4" /></a>@else<div class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-400/20 dark:bg-amber-400/10 dark:text-amber-200">Nomor WhatsApp dukungan belum diisi oleh administrator.</div>@endif</aside>
</div>
@endsection
