@extends('layouts.app')
@php($title = 'Detail Pengguna')
@section('content')
<div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a class="text-sm text-brand-600 dark:text-brand-300" href="{{ route('admin.users.index') }}">← Pengguna</a><h1 class="mt-2 text-3xl font-black">{{ $user->name }}</h1><p class="mt-1 text-sm text-slate-500">{{ $user->email }} · {{ $user->whatsapp }}</p></div><div class="text-right"><x-status :value="$user->status" /><div class="mt-2 text-2xl font-black">Rp {{ number_format((float)$user->balance,0,',','.') }}</div></div></div>

@if($user->deletion_request_status)
<section class="card mt-6 border-amber-200 p-6 dark:border-amber-400/20">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-start">
        <div><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-2xl bg-amber-100 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300"><x-icon name="warning" /></span><div><h2 class="font-black">Permintaan penghapusan akun</h2><p class="text-xs text-slate-500">Status: {{ $user->deletion_request_status }}</p></div></div><p class="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-400">{{ $user->deletion_request_reason ?: 'Tidak ada alasan.' }}</p><p class="mt-2 text-xs text-slate-500">Dikirim {{ $user->deletion_requested_at?->format('d M Y H:i') ?? '—' }}</p></div>
        @if($user->deletion_request_status === 'pending')
        <div class="flex shrink-0 gap-2"><form method="post" action="{{ route('admin.users.deletion-request', $user) }}">@csrf @method('put')<input type="hidden" name="decision" value="reject"><button class="btn-secondary">Tolak</button></form><form method="post" action="{{ route('admin.users.deletion-request', $user) }}" onsubmit="return confirm('Setujui penghapusan? Akun akan dinonaktifkan, sesi dihapus, dan API key dicabut.');">@csrf @method('put')<input type="hidden" name="decision" value="approve"><button class="btn-danger">Setujui</button></form></div>
        @endif
    </div>
</section>
@endif
<div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="card p-6"><h2 class="font-bold">Status akun</h2><form class="mt-4 flex gap-3" method="post" action="{{ route('admin.users.status',$user) }}">@csrf @method('put')<select class="input" name="status">@foreach(['active','suspended','banned'] as $status)<option @selected($user->status===$status)>{{ $status }}</option>@endforeach</select><button class="btn-primary">Simpan</button></form></section><section class="card p-6"><h2 class="font-bold">Penyesuaian saldo</h2><form class="mt-4 grid gap-3 sm:grid-cols-2" method="post" action="{{ route('admin.users.balance',$user) }}">@csrf<select class="input" name="direction"><option value="credit">Tambah saldo</option><option value="debit">Kurangi saldo</option></select><input class="input" type="number" name="amount" min="1" placeholder="Nominal" required><input class="input sm:col-span-2" name="note" placeholder="Alasan penyesuaian" required><button class="btn-primary sm:col-span-2">Proses ledger</button></form></section></div>
<section class="card mt-6 p-5"><h2 class="font-bold">Mutasi terbaru</h2><div class="mt-4 table-wrap"><table class="table"><thead><tr><th>Waktu</th><th>Kategori</th><th>Keterangan</th><th>Nominal</th><th>Saldo</th></tr></thead><tbody>@forelse($transactions as $tx)<tr><td>{{ $tx->created_at->format('d M H:i') }}</td><td>{{ $tx->category }}</td><td>{{ $tx->description }}</td><td class="{{ $tx->direction==='credit'?'text-emerald-500':'text-rose-500' }}">{{ $tx->direction==='credit'?'+':'-' }} Rp {{ number_format((float)$tx->amount,0,',','.') }}</td><td>Rp {{ number_format((float)$tx->balance_after,0,',','.') }}</td></tr>@empty<tr><td colspan="5">Belum ada mutasi.</td></tr>@endforelse</tbody></table></div></section>
<section class="card mt-6 p-5"><h2 class="font-bold">Pesanan terbaru</h2><div class="mt-4 table-wrap"><table class="table"><thead><tr><th>Layanan</th><th>Nomor</th><th>Status</th><th>Harga</th><th></th></tr></thead><tbody>@forelse($orders as $order)<tr><td>{{ $order->service_name }} · {{ $order->country_name }}</td><td>{{ $order->phone_number ?: '—' }}</td><td><x-status :value="$order->status" /></td><td>Rp {{ number_format((float)$order->sell_price,0,',','.') }}</td><td><a href="{{ route('admin.orders.show',$order) }}">Detail</a></td></tr>@empty<tr><td colspan="5">Belum ada pesanan.</td></tr>@endforelse</tbody></table></div></section>
@endsection
